apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: issuer 
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "osmanalbakri54@gmail.com"
    privateKeySecretRef:
      name: issuer 
    solvers:
    - dns01:
        route53:
          hostedZoneID: Z05156923JYRHHGT9YACW
          region: eu-west-2
      selector: 
        dnsZones:
        - "lab.osman2048game.co.uk"
    - http01: 
        ingress:
          class: nginx 