apiVersion: v1
kind: Service
metadata: 
   name: game-2048-service
spec:
    selector:
      app: 2048-eks
    type: ClusterIP
    ports:
    - name: http 
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: app-port
      protocol: TCP
      port: 8096
      targetPort: 3000

---


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: game-2048-ingress
  annotations:
    cert-manager.io/cluster-issuer: "issuer"
spec:
  ingressClassName: nginx
  rules:
  - host: play.lab.osman2048game.co.uk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: game-2048-service
            port:
              number: 80

  tls:
  - hosts:
    - play.lab.osman2048game.co.uk
    secretName: play-tls


    